#! /bin/bash

npm list -g | grep -q 'eslint'

if [ ${PIPESTATUS[1]:-0} -ne 0  ]
then
   sudo npm install -g eslint 
fi

npm list -g | grep -q 'babel-eslint'

if [ ${PIPESTATUS[1]:-0} -ne 0  ]
then
   sudo npm install -g babel-eslint 
fi

npm list -g | grep -q 'eslint-plugin-react'

if [ ${PIPESTATUS[1]:-0} -ne 0  ]
then
   sudo npm install -g eslint-plugin-react 
fi
