#! /bin/bash

if [ $(uname) == 'Darwin' ]
then
	if command -v brew >/dev/null 2>&1; then
	   echo 'homebrew already installed...'
	else
	   echo 'Installing homebrew...'

	   ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi

	echo 'Installing brew packages...'

	~/.carpetbag/bin/brewload
fi
