#! /bin/bash

if command -v node >/dev/null 2>&1; then
   echo 'node installed already...'
else
   echo 'installing node/npm...'

   if [ (uname) == 'Darwin' ]
   then
	   brew install node
   elif [ (uname) == 'Linux' ]
   then
   fi

   echo 'setting path for node modules...'

   # NOTE: we assume node is set up in /usr/local/share/

   echo "PATH=$PATH:/usr/local/share/npm/bin" >> ~/.bashrc
fi

~/.carpetbag/bin/nodeload
