#! /bin/bash

if command -v node >/dev/null 2>&1; then
   echo 'node installed already...'
else
   echo 'installing node/npm...'

   if [ $(uname) == 'Darwin' ]
   then
	   brew install node
   elif [ $(uname) == 'Linux' ]
   then
		# borrowed from SO http://serverfault.com/questions/299288/how-do-you-install-node-js-on-centos
		cd /tmp
		wget http://nodejs.org/dist/node-latest.tar.gz
		tar zxvf node-latest.tar.gz
		cd $(ls -t node* | sort | head -1) 
		./configure
		make
		make install
   fi

   echo 'setting path for node modules...'

   # NOTE: we assume node is set up in /usr/local/share/

   echo "PATH=$PATH:/usr/local/share/npm/bin" >> ~/.bashrc
fi

~/.carpetbag/bin/nodeload
