#! /bin/bash

if command -v node >/dev/null 2>&1; then
   echo 'node installed already...'
else

   if [ $(uname) == 'Darwin' ]
   then
   	   echo 'installing node/npm via brew...'
	   brew install node
   elif command -v apt-get >/dev/null 2>&1;
   then
	   echo 'installing nvm...'
	   curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
   elif [ $(uname) == 'Linux' ]
   then
   	    echo 'installing node/npm the hard way...'
		# borrowed from SO http://serverfault.com/questions/299288/how-do-you-install-node-js-on-centos
		cd /tmp
		wget http://nodejs.org/dist/node-latest.tar.gz -O node-latest.tar.gz
		tar zxvf node-latest.tar.gz
		cd $(ls -t node* | sort | head -1) 
		./configure
		make
		make install
   fi

   echo 'setting path for node modules...'

   # NOTE: we assume node is set up in /usr/local/share/

   echo "PATH=$PATH:/usr/local/share/npm/bin" >> ~/.zshrc
fi

if command -v nvm >/dev/null 2>&1; then
   echo 'nvm installed already...'
else
   echo 'installing nvm...'
   curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
fi

~/.carpetbag/bin/nodeload
