#! /bin/bash

echo "Installing vim-plug..."

mkdir -p ~/.vim/autoload ~/.vim/bundle

if command -v nvim>/dev/null 2>&1; then
	echo 'neovim installed (installing neovim-specific vim-plugin)...'

	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
	echo 'no neovim (installing vim-plugin for generic vim)...'

	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# jshint requires there be a javascript runtime
# if this is running on OSX, everything should be fine,
# but if you are running on Linux, you need to make sure SpiderMonkey is installed

if [ $(uname) == 'Linux' ]; then
	if command -v js >/dev/null 2>&1; then
		echo 'js already installed...'
	else
		echo 'installing js (requires sudo)...'

		if command -v yum >/dev/null 2>&1; then
			sudo yum install js-devel
		else
			echo 'system does not have yum, need to add functionality for whatever package system it uses..'
		fi
	fi
fi


# install silver-searcher
if [ $(uname) == 'Darwin' ]
then
	brew list the_silver_searcher 2>&1 > /dev/null
fi

if command -v ag>/dev/null 2>&1; then
   echo 'silver server installed...'

   install_bundle 'rking/ag.vim'
fi

popd
