#! /bin/bash

echo "Installing pathogen..."

mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -Sso ~/.vim/autoload/pathogen.vim \
    https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim

echo "Add our favorite vim bundles..."

mkdir -p ~/.vim/bundle
pushd ~/.vim/bundle

install_bundle () {
   author_plugin=(${1//\// })

   if [ ! -d ~/.vim/bundle/${author_plugin[1]} ]; then
      git clone https://github.com/$1.git
   fi
}

rm -Rf ~/.vim/bundle/*

install_bundle 'scrooloose/nerdtree'

# jshint requires there be a javascript runtime
# if this is running on OSX, everything should be fine,
# but if you are running on Linux, you need to make sure SpiderMonkey is installed

if [ $(uname) == 'Linux' ]; then
	if command -v js >/dev/null 2>&1; then
		echo 'js already installed...'
	else
		echo 'installing js (requires sudo)...'

		if command -v yum >/dev/null 2>&1; then
			sudo yum install js-devel
		else
			echo 'system does not have yum, need to add functionality for whatever package system it uses..'
		fi
	fi
fi

install_bundle 'vim-scripts/Auto-Pairs'

install_bundle 'flazz/vim-colorschemes'

install_bundle 'yearofmoo/Vim-Darkmate'

install_bundle 'kien/ctrlp.vim'

install_bundle 'tomtom/tcomment_vim'

install_bundle 'editorconfig/editorconfig-vim'

install_bundle 'bling/vim-airline'

install_bundle 'tpope/vim-fugitive'

install_bundle 'Konfekt/FastFold'

install_bundle 'jaawerth/nrun.vim'

install_bundle 'sheerun/vim-polyglot'


# install silver-searcher
if [ $(uname) == 'Darwin' ]
then
	brew list the_silver_searcher 2>&1 > /dev/null
fi

if command -v ag>/dev/null 2>&1; then
   echo 'silver server installed...'

   install_bundle 'rking/ag.vim'
fi

if command -v nvim>/dev/null 2>&1; then
	echo 'neovim installed (installing neovim-specific bundles)...'
	install_bundle 'Shougo/deoplete.nvim'
else
	echo 'no neovim (installing vim-specific bundles)...'
	install_bundle 'w0rp/ale'
	install_bundle 'Shougo/neocomplete'
fi

popd
