#! /bin/bash

echo "Installing pathogen..."

mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -Sso ~/.vim/autoload/pathogen.vim \
    https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim

echo "Add our favorite vim bundles..."

mkdir -p ~/.vim/bundle
pushd ~/.vim/bundle

install_bundle () {
   author_plugin=(${1//\// })

   if [ ! -d ~/.vim/bundle/${author_plugin[1]} ]; then
      git clone https://github.com/$1.git
   fi
}


install_bundle 'scrooloose/nerdtree'

# jshint requires there be a javascript runtime
# if this is running on OSX, everything should be fine,
# but if you are running on Linux, you need to make sure SpiderMonkey is installed

if [ $(uname) == 'Linux' ]; then
	if command -v js >/dev/null 2>&1; then
		echo 'js already installed...'
	else
		echo 'installing js (requires sudo)...'

		if command -v yum >/dev/null 2>&1; then
			sudo yum install js-devel
		else
			echo 'system does not have yum, need to add functionality for whatever package system it uses..'
		fi
	fi
fi

install_bundle 'sleistner/vim-jshint'

install_bundle 'mklabs/grunt'

install_bundle 'vim-scripts/Auto-Pairs'

install_bundle 'jelera/vim-javascript-syntax'

install_bundle 'flazz/vim-colorschemes'

install_bundle 'yearofmoo/Vim-Darkmate'

install_bundle 'vim-scripts/phpfolding.vim'

# the phpfolding library has carriage returns which vim does not like, so clean those up...
tr -d '\r' < ~/.vim/bundle/phpfolding.vim/plugin/phpfolding.vim > ~/.vim/bundle/phpfolding.vim/plugin/phpfolding.vim

install_bundle 'vim-scripts/phpfolding.vim/blob/master/plugin/phpfolding.vim'

install_bundle 'scrooloose/syntastic'

install_bundle 'kien/ctrlp.vim'

install_bundle 'tomtom/tcomment_vim'

install_bundle 'editorconfig/editorconfig-vim'

install_bundle 'derekwyatt/vim-scala'

popd
